_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 14
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
colsample_bytree:
    value: 0.6471211752997611
learning_rate:
    value: 0.11990393518748713
max_depth:
    value: 12
n_estimators:
    value: 266
subsample:
    value: 0.8851452987453599
