name: mlops_env
dependencies:
  - python=3.9
  - pip
  - pip:
      - pandas
      - numpy
      - matplotlib
      - seaborn
      - xgboost
      - wandb
      - mlflow
      - scikit-learn
      - scipy
      - statsmodels
