_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 14
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
colsample_bytree:
    value: 0.9465342421402062
learning_rate:
    value: 0.205136287227922
max_depth:
    value: 6
n_estimators:
    value: 124
subsample:
    value: 0.8239399456191974
